version: "3.8"
services:
  mira:
    build:
      context: ./.docker/dev
    image: jams246/mira:dev
    container_name: mira
    restart: "no"
    stop_grace_period: 1s
    #pid: host #Enable this to see all host processes
    environment:
      PHP_IDE_CONFIG: serverName=Mira
    ports:
      - "80:44356"
      - "44357:44357" #Websocket port
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # [OPTIONAL] Show docker containers
      - "./:/app"